Homework 02
linfel/GSC_App pull request #2
Opened 2020-11-15 18:06 UTC by linfel

* created movie_detail layout

*text | colors are in res-files. All png-s converted to layout

2020-11-15 19:01 UTC, DmitryKolpo commented on app/src/main/res/drawable/ic_path.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Стоит переименовать иконку. Это название из фигмы. Часто в фигме случайные дизайнерские названия, а в проекте придется своими "нормальными" названиями пользоваться

2020-11-15 19:16 UTC, DmitryKolpo commented on app/src/main/res/values/styles.xml
> +    <style name="roboto_bold_14_soft_white">
лучше придерживаться одного стиля написания: либо camelCase, либо snake_case

2020-11-15 19:18 UTC, DmitryKolpo commented
В проекте точно нужен скриншот smol_flopa.webp?

2020-11-15 19:20 UTC, DmitryKolpo commented on app/src/main/res/layout/activity_movie_details.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
Снизу паддинга нет и имена актеров будут впритык к низу.

2020-11-19 16:58 UTC, DmitryKolpo commented on app/src/main/res/drawable/age_restriction_padding.xml
> +</vector>
Погляди про [Shape](https://developer.android.com/guide/topics/resources/drawable-resource#Shape). Будет проще и вариативнее пользоваться этим инструментом.

2020-11-19 17:01 UTC, DmitryKolpo approved these changes

2020-11-19 17:02 UTC, DmitryKolpo approved these changes

2020-11-19 20:18 UTC, T-228 commented
check

2020-11-19 20:21 UTC, pavelmaslov commented
Я ничего не понял

2020-11-19 20:24 UTC, pavelmaslov reviewed
я ничего не понял

2020-11-19 20:28 UTC, pavelmaslov requested changes
я ничего не понял

2020-11-19 20:28 UTC, pavelmaslov commented on .idea/gradle.xml
> +        <option name="disableWrapperSourceDistributionNotification" value="true" />
я все еще ничего не понял
```suggestion
        <option name="disableWrapperSourceDistributionNotification" value="no" />
```

2020-11-19 20:30 UTC, linfel commented on .idea/gradle.xml
> +        <option name="disableWrapperSourceDistributionNotification" value="true" />
все понятно

2020-11-19 20:32 UTC, pavelmaslov approved these changes
Благославляю

2020-11-19 20:32 UTC, pavelmaslov approved these changes
Теперь точно апруваю, сын мой

2020-11-19 20:49 UTC, pavelmaslov approved these changes
нук попробую еще раз АПРУУУУУУВ

2020-11-19 20:52 UTC, pavelmaslov requested changes

2020-11-19 20:52 UTC, pavelmaslov commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
Тебе сука меня уговаривать не придется. Где тут код какой-нибудь
```suggestion
    androidTestImplementation 'androidx.prolaps.espresso:espresso-core:3.3.0'
```

2020-11-19 20:53 UTC, pavelmaslov commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
А лан оставь так))

2020-11-19 20:53 UTC, pavelmaslov approved these changes

2020-11-19 20:54 UTC, pavelmaslov commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
Оп заанрезолвил как тебе такое илон маск

2020-11-19 20:54 UTC, merged